# Generated by Django 4.2.6 on 2023-10-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='findings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200)),
                ('p_phone', models.CharField(max_length=10)),
                ('doc_name', models.CharField(max_length=200)),
                ('booking_date', models.DateField()),
            ],
        ),
    ]
